spring.application.name=transporte-uni

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/transportedb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.open-in-view
spring.jpa.hibernate.ddl-auto=update
